services:
  vtuber-nook-bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${BOT_WEBHOOK_PORT:-3010}:3010"
    environment:
      TOKEN: "${TOKEN}"
      OWNERIDS: "${OWNERIDS}"
      BOT_WEBHOOK_PORT: "${BOT_WEBHOOK_PORT:-3010}"
      BOT_WEBHOOK_SECRET: "${BOT_WEBHOOK_SECRET}"
      BOT_NOTIFY_CHANNEL_ID: "${BOT_NOTIFY_CHANNEL_ID}"
      BOT_NOTIFY_CHANNEL_REPORTS: "${BOT_NOTIFY_CHANNEL_REPORTS}"
      BOT_NOTIFY_CHANNEL_SUBMISSIONS: "${BOT_NOTIFY_CHANNEL_SUBMISSIONS}"
      BOT_NOTIFY_CHANNEL_FEATURED: "${BOT_NOTIFY_CHANNEL_FEATURED}"
      BOT_NOTIFY_CHANNEL_PUBLISHED: "${BOT_NOTIFY_CHANNEL_PUBLISHED}"
      BOT_WELCOME_CHANNEL_ID: "${BOT_WELCOME_CHANNEL_ID}"
      BOT_WELCOME_RULES_CHANNEL_ID: "${BOT_WELCOME_RULES_CHANNEL_ID}"
      BOT_ROLES_CHANNEL_ID: "${BOT_ROLES_CHANNEL_ID}"
      BOT_WELCOME_INTRO_CHANNEL_ID: "${BOT_WELCOME_INTRO_CHANNEL_ID}"
      BOT_WELCOME_IMAGE_URL: "${BOT_WELCOME_IMAGE_URL}"
      BOT_LEAVE_CHANNEL_ID: "${BOT_LEAVE_CHANNEL_ID}"
      BOT_LEAVE_IMAGE_URL: "${BOT_LEAVE_IMAGE_URL}"
    healthcheck:
      disable: true
    restart: unless-stopped
